# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
fit_dpsbm <- function(A, gam0 = 1, alpha = 1, beta = 1, niter = 50L, Zcap = 20L, verb = TRUE, slice = FALSE) {
    .Call(`_hsbm_fit_dpsbm`, A, gam0, alpha, beta, niter, Zcap, verb, slice)
}

#' @export
fit_mult_dpsbm <- function(A, gam0 = 1, alpha = 1, beta = 1, niter = 50L, Zcap = 20L, verb = TRUE, slice = FALSE) {
    .Call(`_hsbm_fit_mult_dpsbm`, A, gam0, alpha, beta, niter, Zcap, verb, slice)
}

#' @export
fit_hsbm <- function(A, beta0 = 0.1, gam0 = 0.5, alpha_eta = 1, beta_eta = 5, niter = 50L, Kcap = 10L, Gcap = 10L, verb = TRUE, rand_init = TRUE, seq_g_update = TRUE) {
    .Call(`_hsbm_fit_hsbm`, A, beta0, gam0, alpha_eta, beta_eta, niter, Kcap, Gcap, verb, rand_init, seq_g_update)
}

update_eta <- function(Alist, n, zb, alpha_eta, beta_eta, Kcap) {
    .Call(`_hsbm_update_eta`, Alist, n, zb, alpha_eta, beta_eta, Kcap)
}

multsbm_gibbs_sampler_fast <- function(A, K, alpha = 1, beta = 1, niter = 100L) {
    .Call(`_hsbm_multsbm_gibbs_sampler_fast`, A, K, alpha, beta, niter)
}

sample_int <- function(N) {
    .Call(`_hsbm_sample_int`, N)
}

sample_int_vec <- function(N, size) {
    .Call(`_hsbm_sample_int_vec`, N, size)
}

stick_break <- function(x) {
    .Call(`_hsbm_stick_break`, x)
}

symmat_rbeta <- function(alpha, beta) {
    .Call(`_hsbm_symmat_rbeta`, alpha, beta)
}

safe_exp <- function(log_prob) {
    .Call(`_hsbm_safe_exp`, log_prob)
}

my_sampler <- function(prob_vec) {
    .Call(`_hsbm_my_sampler`, prob_vec)
}

sample_index <- function(prob) {
    .Call(`_hsbm_sample_index`, prob)
}

rgamma_vec <- function(shape) {
    .Call(`_hsbm_rgamma_vec`, shape)
}

rbeta_vec <- function(alpha, beta) {
    .Call(`_hsbm_rbeta_vec`, alpha, beta)
}

rdirichlet <- function(theta) {
    .Call(`_hsbm_rdirichlet`, theta)
}

gem_gibbs_update <- function(z, Zcap, concent_param) {
    .Call(`_hsbm_gem_gibbs_update`, z, Zcap, concent_param)
}

get_up_freq <- function(freq) {
    .Call(`_hsbm_get_up_freq`, freq)
}

find_tunc <- function(beta, threshold) {
    .Call(`_hsbm_find_tunc`, beta, threshold)
}

fast_agg <- function(x, z, K) {
    .Call(`_hsbm_fast_agg`, x, z, K)
}

get_freq <- function(z, K) {
    .Call(`_hsbm_get_freq`, z, K)
}

get_freq_minus_self <- function(z, K) {
    .Call(`_hsbm_get_freq_minus_self`, z, K)
}

comp_blk_sums <- function(At, z, Kcap) {
    .Call(`_hsbm_comp_blk_sums`, At, z, Kcap)
}

sp_compress_col <- function(At, z, Kcap) {
    .Call(`_hsbm_sp_compress_col`, At, z, Kcap)
}

sp_single_col_compress <- function(A, col_idx, z, Kcap) {
    .Call(`_hsbm_sp_single_col_compress`, A, col_idx, z, Kcap)
}

comp_blk_sums_and_sizes <- function(At, z, Kcap, div_diag = TRUE) {
    .Call(`_hsbm_comp_blk_sums_and_sizes`, At, z, Kcap, div_diag)
}

iter_over_sp_mat <- function(At) {
    invisible(.Call(`_hsbm_iter_over_sp_mat`, At))
}

